services:
 web:
  build: .
  container_name: django_app
  command: gunicorn logistic.wsgi:application --bind 0.0.0.0:8000
  volumes:
   - .:/app
  env_file:
   - .env
  depends_on:
   - db
  networks:
   - mynetwork

 db:
  image: postgres:13
  container_name: postgres_db
  environment:
   POSTGRES_DB: django_app
   POSTGRES_USER: irina
   POSTGRES_PASSWORD: 123
  volumes:
   - postgres_data:/var/lib/postgresql/data
  networks:
   - mynetwork

 nginx:
  image: nginx:latest
  container_name: nginx_server
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
   - "80:80"
  depends_on:
   - web
  networks:
   - mynetwork

networks:
 mynetwork:
  driver: bridge

volumes:
 postgres_data:









